use AccountantDB;
go

-- ALTERING TABLES -- 

-- INVOICES---

ALTER TABLE INVOICES
ALTER COLUMN INV_BRU_VAL DECIMAL(10,2);
ALTER TABLE INVOICES
ALTER COLUMN INV_NET_VAL DECIMAL(10,2);
ALTER TABLE INVOICES
ALTER COLUMN INV_VAT DECIMAL(5,2);
go
---INVOICES_ARCH---

ALTER TABLE INVOICES_ARCH
ALTER COLUMN NEW_INV_BRU_VAL DECIMAL(10,2);
ALTER TABLE INVOICES_ARCH
ALTER COLUMN OLD_INV_BRU_VAL DECIMAL(10,2);

ALTER TABLE  INVOICES_ARCH
ALTER COLUMN NEW_INV_NET_VAL DECIMAL(10,2);
ALTER TABLE  INVOICES_ARCH
ALTER COLUMN OLD_INV_NET_VAL DECIMAL(10,2);

ALTER TABLE  INVOICES_ARCH
ALTER COLUMN NEW_INV_VAT DECIMAL(5,2);
ALTER TABLE  INVOICES_ARCH
ALTER COLUMN OLD_INV_VAT DECIMAL(5,2);
go