use AccountantDB;
go

CREATE TABLE LAWYERS
	(
		ID		INT PRIMARY KEY	NOT NULL,
		NAME	NVARCHAR(50),
		SURNAME	NVARCHAR(50),
		SALARY	DECIMAL(10,2),
		HIREDATE	DATE NOT NULL		
	);
	
ALTER TABLE LAWYERS
ADD COMM DECIMAL(10,2);


CREATE TABLE DEPARTMENTS
	(
		ID_DEPARTMENTS	INT PRIMARY KEY NOT NULL,
		DEPT_NAME		NVARCHAR(255) NOT NULL,
		DEPT_MGR		INT
	);

SELECT * FROM DEPARTMENTS;
go


CREATE TABLE INVOICES
	(
		ID_INVOICES	INT PRIMARY KEY NOT NULL,
		INV_NUMBER	NVARCHAR,
		INV_OWNER	NVARCHAR(50),
		INV_PROJECT	INT,
		INV_NET_VAL	INT,
		INV_VAT		INT,
		INV_BRU_VAL	INT,
		INV_DATE	DATE,
		INV_PAYDAY	DATE
	);
ALTER TABLE INVOICES
ADD CONSTRAINT unique_inv_number UNIQUE (INV_NUMBER);

ALTER TABLE INVOICES
ALTER COLUMN INV_BRU_VAL DECIMAL(10,2);
ALTER TABLE INVOICES
ALTER COLUMN INV_NET_VAL DECIMAL(10,2);
ALTER TABLE INVOICES
ALTER COLUMN INV_VAT DECIMAL(5,2);

UPDATE INVOICES
SET INV_BRU_VAL = NULL;

SELECT * FROM invoices

CREATE TABLE PROJECTS
	(
		ID_PROJECTS	INT PRIMARY KEY NOT NULL,
		PROJ_NAME	NVARCHAR(255),
		PROJ_MGR	INT
	);
	SELECT * FROM PROJECTS_ARCH

CREATE TABLE LAWYERS_ARCH
	(
		ID_LAWYERS_ARCH	INT PRIMARY KEY	NOT NULL,
		NEW_NAME		NVARCHAR(50),
		NEW_SURNAME		NVARCHAR(50),
		NEW_SALARY		INT,
		NEW_HIREDATE	DATE, 
		OLD_NAME		NVARCHAR(50),
		OLD_SURNAME		NVARCHAR(50),
		OLD_SALARY		INT,
		OLD_HIREDATE	DATE,
		CHANGE_TIME		DATETIME	NOT NULL,
		OPERATION_TYPE	NVARCHAR(6) NOT NULL
	);

	SELECT * FROM LAWYERS_ARCH


CREATE TABLE DEPARTMENTS_ARCH
	(
		ID_DEPARTMENTS_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_DEPT_NAME		NVARCHAR(255) NOT NULL,
		NEW_DEPT_MGR		INT,
		OLD_DEPT_NAME		NVARCHAR(255) NOT NULL,
		OLD_DEPT_MGR		INT,
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);

CREATE TABLE INVOICES_ARCH
	(
		ID_INVOICES_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_INV_NUMBER		NVARCHAR,
		NEW_INV_OWNER		NVARCHAR(50),
		NEW_INV_PROJECT		INT,
		NEW_INV_NET_VAL		INT,
		NEW_INV_VAT			INT,
		NEW_INV_BRU_VAL		INT,
		NEW_INV_DATE		DATE,
		NEW_INV_PAYDAY		DATE,
		NEW_INV_PROJ_ID		INT,
		NEW_INV_TYPE		NVARCHAR(6),
		NEW_INV_CLIENT_ID	INT,
		NEW_INV_STATUS		NVARCHAR(7),
		OLD_INV_NUMBER		NVARCHAR,
		OLD_INV_OWNER		NVARCHAR(50),
		OLD_INV_PROJECT		INT,
		OLD_INV_NET_VAL		INT,
		OLD_INV_VAT			INT,
		OLD_INV_BRU_VAL		INT,
		OLD_INV_DATE		DATE,
		OLD_INV_PAYDAY		DATE,
		OLD_INV_PROJ_ID		INT,
		OLD_INV_TYPE		NVARCHAR(6),
		OLD_INV_CLIENT_ID	INT,
		OLD_INV_STATUS		NVARCHAR(7),
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);

	ALTER TABLE INVOICES_ARCH
	ALTER COLUMN NEW_INV_BRU_VAL DECIMAL(10,2);
	ALTER TABLE INVOICES_ARCH
	ALTER COLUMN OLD_INV_BRU_VAL DECIMAL(10,2);

	ALTER TABLE  INVOICES_ARCH
	ALTER COLUMN NEW_INV_NET_VAL DECIMAL(10,2);
	ALTER TABLE  INVOICES_ARCH
	ALTER COLUMN OLD_INV_NET_VAL DECIMAL(10,2);

	ALTER TABLE  INVOICES_ARCH
	ALTER COLUMN NEW_INV_VAT DECIMAL(5,2);
	ALTER TABLE  INVOICES_ARCH
	ALTER COLUMN OLD_INV_VAT DECIMAL(5,2);


CREATE TABLE PROJECTS_ARCH
	(
		ID_PROJECTS_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_PROJ_NAME		NVARCHAR(255),
		NEW_PROJ_MGR		INT,
		OLD_PROJ_NAME		NVARCHAR(255),
		OLD_PROJ_MGR		INT,
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);

CREATE TABLE CLIENTS
	(
		ID_CLIENTS	INT PRIMARY KEY	NOT NULL,
		CLIENT_NAME	NVARCHAR(50)
	);

CREATE TABLE CLIENTS_ARCH
	(
		ID_CLIENTS_ARCH		INT PRIMARY KEY	NOT NULL,
		NEW_CLIENT_NAME		NVARCHAR(50),
		OLD_CLIENT_NAME		NVARCHAR(50),
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);
