-- CREATING TABLES -- 

CREATE TABLE LAWYERS
	(
		ID			INT PRIMARY KEY	NOT NULL,
		NAME		NVARCHAR(50),
		SURNAME		NVARCHAR(50),
		SALARY		DECIMAL(10,2),
		HIREDATE	DATE NOT NULL,
		COMM		DECIMAL(10,2)
	);


CREATE TABLE DEPARTMENTS
	(
		ID_DEPARTMENTS	INT PRIMARY KEY NOT NULL,
		DEPT_NAME		NVARCHAR(255),
		DEPT_MGR		INT
	);

CREATE TABLE INVOICES
	(
		ID_INVOICES		INT PRIMARY KEY NOT NULL,
		INV_NUMBER		NVARCHAR,
		INV_OWNER		INT,
		INV_PROJ_ID		INT,
		INV_CLIENT_ID	INT,
		INV_NET_VAL		INT,
		INV_VAT			INT,
		INV_BRU_VAL		INT,
		INV_DATE		DATE,
		INV_PAYDAY		DATE,
		INV_TYPE		NVARCHAR(6),
		INV_STATUS		NVARCHAR(7)
	);


CREATE TABLE PROJECTS
	(
		ID_PROJECTS		INT PRIMARY KEY NOT NULL,
		PROJ_NAME		NVARCHAR(255),
		PROJ_MGR		INT,
		PROJ_BUDGET		INT,
		PROJ_CLIENT_ID	INT,
		PROJ_DEPT_ID	INT,
		PROJ_START		DATE,
		PROJ_END		DATE
	);


CREATE TABLE LAWYERS_ARCH
	(
		ID_LAWYERS_ARCH	INT PRIMARY KEY	NOT NULL,
		NEW_NAME		NVARCHAR(50),
		NEW_SURNAME		NVARCHAR(50),
		NEW_SALARY		INT,
		NEW_HIREDATE	DATE, 
		OLD_NAME		NVARCHAR(50),
		OLD_SURNAME		NVARCHAR(50),
		OLD_SALARY		INT,
		OLD_HIREDATE	DATE,
		CHANGE_TIME		DATETIME	NOT NULL,
		OPERATION_TYPE	NVARCHAR(6) NOT NULL
	);


CREATE TABLE DEPARTMENTS_ARCH
	(
		ID_DEPARTMENTS_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_DEPT_NAME		NVARCHAR(255),
		NEW_DEPT_MGR		INT,
		OLD_DEPT_NAME		NVARCHAR(255),
		OLD_DEPT_MGR		INT,
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);

CREATE TABLE INVOICES_ARCH
	(
		ID_INVOICES_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_INV_NUMBER		NVARCHAR,
		NEW_INV_OWNER		INT,
		NEW_INV_NET_VAL		INT,
		NEW_INV_VAT			INT,
		NEW_INV_BRU_VAL		INT,
		NEW_INV_DATE		DATE,
		NEW_INV_PAYDAY		DATE,
		NEW_INV_PROJ_ID		INT,
		NEW_INV_TYPE		NVARCHAR(6),
		NEW_INV_CLIENT_ID	INT,
		NEW_INV_STATUS		NVARCHAR(7),
		OLD_INV_NUMBER		NVARCHAR,
		OLD_INV_OWNER		INT,
		OLD_INV_NET_VAL		INT,
		OLD_INV_VAT			INT,
		OLD_INV_BRU_VAL		INT,
		OLD_INV_DATE		DATE,
		OLD_INV_PAYDAY		DATE,
		OLD_INV_PROJ_ID		INT,
		OLD_INV_TYPE		NVARCHAR(6),
		OLD_INV_CLIENT_ID	INT,
		OLD_INV_STATUS		NVARCHAR(7),
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);



CREATE TABLE PROJECTS_ARCH
	(
		ID_PROJECTS_ARCH	INT PRIMARY KEY NOT NULL,
		NEW_PROJ_NAME		NVARCHAR(255),
		NEW_PROJ_MGR		INT,
		NEW_PROJ_BUDGET		INT,
		NEW_PROJ_CLIENT_ID	INT,
		NEW_PROJ_DEPT_ID	INT,
		NEW_PROJ_START		DATE,
		NEW_PROJ_END		DATE,
		OLD_PROJ_NAME		NVARCHAR(255),
		OLD_PROJ_MGR		INT,
		OLD_PROJ_BUDGET		INT,
		OLD_PROJ_CLIENT_ID	INT,
		OLD_PROJ_DEPT_ID	INT,
		OLD_PROJ_START		DATE,
		OLD_PROJ_END		DATE,
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);


CREATE TABLE CLIENTS
	(
		ID_CLIENTS	INT PRIMARY KEY	NOT NULL,
		CLIENT_NAME	NVARCHAR(50)
	);

CREATE TABLE CLIENTS_ARCH
	(
		ID_CLIENTS_ARCH		INT PRIMARY KEY	NOT NULL,
		NEW_CLIENT_NAME		NVARCHAR(50),
		OLD_CLIENT_NAME		NVARCHAR(50),
		CHANGE_TIME			DATETIME	NOT NULL,
		OPERATION_TYPE		NVARCHAR(6) NOT NULL
	);
go
