use AccountantDB

CREATE SEQUENCE lawyers_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE dept_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE projects_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE invoices_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE clients_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE lawyers_arch_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE dept_arch_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE projects_arch_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE invoices_arch_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;
CREATE SEQUENCE clients_arch_id_seq START WITH 1 INCREMENT BY 1 NO CACHE;

SELECT NEXT VALUE FOR lawyers_id_seq

